# Tiền xử lí dữ liệu

In [9]:
import pandas as pd
import re

df = pd.read_csv('../data/raw_data/ddinter2_dfi_data.csv')

df.head()

,drug_name,food_name,severity,description,source
0,Calcium lactate,spinach,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
1,Calcium lactate,rhubarb,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
2,Calcium lactate,bran,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
3,Calcium lactate,grain,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
4,Pralsetinib,high-fat foods,Major,Food significantly increases the oral bioavail...,"""Product Information. Gavreto (pralsetinib)."" ..."

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   drug_name    857 non-null    str
 1   food_name    857 non-null    str
 2   severity     857 non-null    str
 3   description  857 non-null    str
 4   source       857 non-null    str
dtypes: str(5)
memory usage: 33.6 KB

## Kiểm tra rỗng và lặp

In [11]:
# kiểm tra dòng rỗng
df.isnull().sum()

drug_name      0
food_name      0
severity       0
description    0
source         0
dtype: int64

In [12]:
# Kiểm tra trùng lặp
df.duplicated().sum()

np.int64(0)

## Chuẩn hóa text

In [13]:
def clean_text(text):
    text = str(text).lower().strip()
    text = re.sub(r'[^a-z0-9\s]','',text) #bỏ kí tự không phải chữ/số/khoảng trắng
    text = re.sub(r'\s+',' ',text)
    return text

df["drug_name"] = df["drug_name"].apply(clean_text)
df["food_name"] = df["food_name"].apply(clean_text)

# description,source chỉ cần bỏ khoảng trắng 
df["description"] = df["description"].apply(lambda x: str(x).strip()) 
df["source"] = df["source"].apply(lambda x: str(x).strip())

df.head()

,drug_name,food_name,severity,description,source
0,calcium lactate,spinach,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
1,calcium lactate,rhubarb,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
2,calcium lactate,bran,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
3,calcium lactate,grain,Moderate,Administration with food may increase the abso...,"Cerner Multum, Inc. ""UK Summary of Product Cha..."
4,pralsetinib,highfat foods,Major,Food significantly increases the oral bioavail...,"""Product Information. Gavreto (pralsetinib)."" ..."

## Chuẩn hóa cột severity

In [14]:
def normalize_severity(x):
    x = str(x).lower()

    if "major" in x:
        return "High"
    elif "minor" in x:
        return "Low"
    else:
        return "Moderate"
    
df['severity'] = df['severity'].apply(normalize_severity)

print(df["severity"].value_counts())

severity
Moderate    714
High        105
Low          38
Name: count, dtype: int64

In [15]:
print(df.head())
print(df["severity"].value_counts())
print(df.info())

         drug_name      food_name  severity  \
0  calcium lactate        spinach  Moderate
1  calcium lactate        rhubarb  Moderate
2  calcium lactate           bran  Moderate
3  calcium lactate          grain  Moderate
4      pralsetinib  highfat foods      High

                                         description  \
0  Administration with food may increase the abso...
1  Administration with food may increase the abso...
2  Administration with food may increase the abso...
3  Administration with food may increase the abso...
4  Food significantly increases the oral bioavail...

                                              source
0  Cerner Multum, Inc. "UK Summary of Product Cha...
1  Cerner Multum, Inc. "UK Summary of Product Cha...
2  Cerner Multum, Inc. "UK Summary of Product Cha...
3  Cerner Multum, Inc. "UK Summary of Product Cha...
4  "Product Information. Gavreto (pralsetinib)." ...
severity
Moderate    714
High        105
Low          38
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   drug_name    857 non-null    str
 1   food_name    857 non-null    str
 2   severity     857 non-null    str
 3   description  857 non-null    str
 4   source       857 non-null    str
dtypes: str(5)
memory usage: 33.6 KB
None

## EXPORT CLEAN DATASET

In [17]:
df.to_csv("../data/clean_data/clean_ddinter_data.csv", index=False)
print("Saved: clean_ddinter_data.csv")

Saved: clean_ddinter_data.csv